name: Deploy docs

on:
  push:
    branches:
      - main
    paths:
      - docs/**/*
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy documentation
        uses: wei/curl@master
        with:
          args: -X GET ${{ secrets.DEPLOYMENT_URL }}
